/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Leads
         * @description Get leads with optional filters.
         */
        get: operations["get_leads_api_leads_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leads/recently-promoted": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Leads Recently Promoted
         * @description Get leads who were recently promoted.
         */
        get: operations["get_leads_recently_promoted_api_leads_recently_promoted_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leads/new-in-role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Leads New In Role
         * @description Get leads who recently started a new role.
         */
        get: operations["get_leads_new_in_role_api_leads_new_in_role_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leads/at-vc-portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Leads At Vc Portfolio
         * @description Get leads at VC portfolio companies.
         */
        get: operations["get_leads_at_vc_portfolio_api_leads_at_vc_portfolio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leads/by-past-employer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Leads By Past Employer
         * @description Get leads who previously worked at specified companies.
         *
         *     Uses PostgreSQL function core.get_leads_by_past_employer() for efficient querying.
         */
        get: operations["get_leads_by_past_employer_api_leads_by_past_employer_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leads/by-company-customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Leads By Company Customers
         * @description Get leads who previously worked at customers of the specified company.
         *
         *     Looks up the company's customers from core.company_customers, then finds
         *     leads who have work history at those customer companies.
         */
        get: operations["get_leads_by_company_customers_api_leads_by_company_customers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/filters/job-functions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job Functions
         * @description Get all available job functions for filter dropdowns.
         */
        get: operations["get_job_functions_api_filters_job_functions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/filters/seniorities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Seniorities
         * @description Get all available seniority levels for filter dropdowns.
         */
        get: operations["get_seniorities_api_filters_seniorities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/filters/industries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Industries
         * @description Get all available industries for filter dropdowns.
         */
        get: operations["get_industries_api_filters_industries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/filters/employee-ranges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Employee Ranges
         * @description Get all available employee ranges for filter dropdowns.
         */
        get: operations["get_employee_ranges_api_filters_employee_ranges_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/filters/vc-firms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Vc Firms
         * @description Get all available VC firm names for filter dropdowns.
         */
        get: operations["get_vc_firms_api_filters_vc_firms_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/filters/person-countries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Person Countries
         * @description Get all available person countries for filter dropdowns.
         */
        get: operations["get_person_countries_api_filters_person_countries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/filters/person-states": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Person States
         * @description Get all available person states for filter dropdowns.
         */
        get: operations["get_person_states_api_filters_person_states_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** FilterOption */
        FilterOption: {
            /** Value */
            value: string;
            /** Count */
            count: number;
        };
        /** FiltersResponse */
        FiltersResponse: {
            /** Data */
            data: components["schemas"]["FilterOption"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Lead */
        Lead: {
            /** Person Id */
            person_id?: string | null;
            /** Linkedin Url */
            linkedin_url?: string | null;
            /** Linkedin Slug */
            linkedin_slug?: string | null;
            /** Full Name */
            full_name?: string | null;
            /** Linkedin Url Type */
            linkedin_url_type?: string | null;
            /** Linkedin User Profile Urn */
            linkedin_user_profile_urn?: string | null;
            /** Person City */
            person_city?: string | null;
            /** Person State */
            person_state?: string | null;
            /** Person Country */
            person_country?: string | null;
            /** Matched Cleaned Job Title */
            matched_cleaned_job_title?: string | null;
            /** Matched Job Function */
            matched_job_function?: string | null;
            /** Matched Seniority */
            matched_seniority?: string | null;
            /** Job Start Date */
            job_start_date?: string | null;
            /** Company Id */
            company_id?: string | null;
            /** Company Domain */
            company_domain?: string | null;
            /** Company Name */
            company_name?: string | null;
            /** Company Linkedin Url */
            company_linkedin_url?: string | null;
            /** Company City */
            company_city?: string | null;
            /** Company State */
            company_state?: string | null;
            /** Company Country */
            company_country?: string | null;
            /** Matched Industry */
            matched_industry?: string | null;
            /** Employee Range */
            employee_range?: string | null;
        };
        /** LeadAtVCPortfolio */
        LeadAtVCPortfolio: {
            /** Person Id */
            person_id?: string | null;
            /** Linkedin Url */
            linkedin_url?: string | null;
            /** Linkedin Slug */
            linkedin_slug?: string | null;
            /** Full Name */
            full_name?: string | null;
            /** Linkedin Url Type */
            linkedin_url_type?: string | null;
            /** Linkedin User Profile Urn */
            linkedin_user_profile_urn?: string | null;
            /** Person City */
            person_city?: string | null;
            /** Person State */
            person_state?: string | null;
            /** Person Country */
            person_country?: string | null;
            /** Matched Cleaned Job Title */
            matched_cleaned_job_title?: string | null;
            /** Matched Job Function */
            matched_job_function?: string | null;
            /** Matched Seniority */
            matched_seniority?: string | null;
            /** Job Start Date */
            job_start_date?: string | null;
            /** Company Id */
            company_id?: string | null;
            /** Company Domain */
            company_domain?: string | null;
            /** Company Name */
            company_name?: string | null;
            /** Company Linkedin Url */
            company_linkedin_url?: string | null;
            /** Company City */
            company_city?: string | null;
            /** Company State */
            company_state?: string | null;
            /** Company Country */
            company_country?: string | null;
            /** Matched Industry */
            matched_industry?: string | null;
            /** Employee Range */
            employee_range?: string | null;
            /** Vc Name */
            vc_name?: string | null;
            /** Vc Company Description */
            vc_company_description?: string | null;
        };
        /** LeadRecentlyPromoted */
        LeadRecentlyPromoted: {
            /** Person Id */
            person_id?: string | null;
            /** Linkedin Url */
            linkedin_url?: string | null;
            /** Linkedin Slug */
            linkedin_slug?: string | null;
            /** Full Name */
            full_name?: string | null;
            /** Linkedin Url Type */
            linkedin_url_type?: string | null;
            /** Linkedin User Profile Urn */
            linkedin_user_profile_urn?: string | null;
            /** Person City */
            person_city?: string | null;
            /** Person State */
            person_state?: string | null;
            /** Person Country */
            person_country?: string | null;
            /** Matched Cleaned Job Title */
            matched_cleaned_job_title?: string | null;
            /** Matched Job Function */
            matched_job_function?: string | null;
            /** Matched Seniority */
            matched_seniority?: string | null;
            /** Job Start Date */
            job_start_date?: string | null;
            /** Company Id */
            company_id?: string | null;
            /** Company Domain */
            company_domain?: string | null;
            /** Company Name */
            company_name?: string | null;
            /** Company Linkedin Url */
            company_linkedin_url?: string | null;
            /** Company City */
            company_city?: string | null;
            /** Company State */
            company_state?: string | null;
            /** Company Country */
            company_country?: string | null;
            /** Matched Industry */
            matched_industry?: string | null;
            /** Employee Range */
            employee_range?: string | null;
            /** Previous Title */
            previous_title?: string | null;
            /** New Title */
            new_title?: string | null;
            /** Promotion Date */
            promotion_date?: string | null;
        };
        /** LeadsAtVCPortfolioResponse */
        LeadsAtVCPortfolioResponse: {
            /** Data */
            data: components["schemas"]["LeadAtVCPortfolio"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        /** LeadsRecentlyPromotedResponse */
        LeadsRecentlyPromotedResponse: {
            /** Data */
            data: components["schemas"]["LeadRecentlyPromoted"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        /** LeadsResponse */
        LeadsResponse: {
            /** Data */
            data: components["schemas"]["Lead"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        /** PaginationMeta */
        PaginationMeta: {
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_leads_api_leads_get: {
        parameters: {
            query?: {
                /** @description Filter by job function (comma-separated) */
                job_function?: string | null;
                /** @description Filter by seniority (comma-separated) */
                seniority?: string | null;
                /** @description Filter by industry (comma-separated) */
                industry?: string | null;
                /** @description Filter by employee range (comma-separated) */
                employee_range?: string | null;
                person_city?: string | null;
                person_state?: string | null;
                person_country?: string | null;
                company_city?: string | null;
                company_state?: string | null;
                company_country?: string | null;
                company_domain?: string | null;
                company_name?: string | null;
                job_title?: string | null;
                full_name?: string | null;
                job_start_date_gte?: string | null;
                job_start_date_lte?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_leads_recently_promoted_api_leads_recently_promoted_get: {
        parameters: {
            query?: {
                promoted_within_days?: number;
                job_function?: string | null;
                seniority?: string | null;
                industry?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadsRecentlyPromotedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_leads_new_in_role_api_leads_new_in_role_get: {
        parameters: {
            query?: {
                started_within_days?: number;
                job_function?: string | null;
                seniority?: string | null;
                industry?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_leads_at_vc_portfolio_api_leads_at_vc_portfolio_get: {
        parameters: {
            query?: {
                /** @description Filter by VC firm name */
                vc_name?: string | null;
                job_function?: string | null;
                seniority?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadsAtVCPortfolioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_leads_by_past_employer_api_leads_by_past_employer_get: {
        parameters: {
            query: {
                /** @description Comma-separated list of company domains */
                domains: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_leads_by_company_customers_api_leads_by_company_customers_get: {
        parameters: {
            query: {
                /** @description Domain of the origin company (e.g., 'forethought.ai') */
                company_domain: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_functions_api_filters_job_functions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FiltersResponse"];
                };
            };
        };
    };
    get_seniorities_api_filters_seniorities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FiltersResponse"];
                };
            };
        };
    };
    get_industries_api_filters_industries_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FiltersResponse"];
                };
            };
        };
    };
    get_employee_ranges_api_filters_employee_ranges_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FiltersResponse"];
                };
            };
        };
    };
    get_vc_firms_api_filters_vc_firms_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FiltersResponse"];
                };
            };
        };
    };
    get_person_countries_api_filters_person_countries_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FiltersResponse"];
                };
            };
        };
    };
    get_person_states_api_filters_person_states_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FiltersResponse"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
